INTEGER = "INTEGER"
TEXT = "TEXT"
DATETIME = "DATETIME"
VARCHAR = "VARCHAR"
BOOL = "BOOL"
TIMESTAMP = "TIMESTAMP"


class DATATYPES:
    INTEGER = INTEGER
    TEXT = TEXT
    DATETIME = DATETIME
    VARCHAR = VARCHAR
    BOOL = BOOL
    TIMESTAMP = TIMESTAMP
